security:

  providers:
    our_db_provider:
      entity:
        class : App\Entity\User
        property : username
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
        entity:
            class: App\Entity\User
            property: username
  firewalls:
    main:
      pattern: ^/
      provider: our_db_provider
      anonymous: ~
      form_login:
        login_path: /user/login
        check_path: /user/login
      logout:
        path: /user/logout
        target: home
      guard:
          authenticators:
              - App\Security\AppAuthentificator

  encoders:
    App\Entity\User:
      algorithm: auto



  access_control:
    - { path: '^/admin', roles: ROLE_ADMIN }
