security:

  providers:
    our_db_provider:
      entity:
        class : App\Entity\User
        property : username
  firewalls:
    main:
      pattern: ^/
      provider: our_db_provider
      anonymous: ~
      form_login:
        login_path: /user/login
        check_path: /user/login
      logout:
        path: /user/logout
        target: home

  encoders:
    App\Entity\User:
      algorithm: bcrypt


  access_control:
    - { path: '^/admin', roles: ROLE_ADMIN }
